<a href="https://colab.research.google.com/github/StepanTol/Google-Colab-Lesson9/blob/main/HW1_Lesson10%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца.
Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

import random
import pandas as pd

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

data.head()

In [ ]:
import random
import pandas as pd

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

data.head()

  whoAmI
0  robot
1  human
2  human
3  robot
4  robot

Вариант №1

In [ ]:
lst = []
for val in data.whoAmI:
    if val == 'robot':
      lst.append([1, 0])
    else:
      lst.append([0, 1])

df = pd.DataFrame(lst, columns = ['robot', 'human'])
df.head()

   robot  human
0      1      0
1      0      1
2      0      1
3      1      0
4      1      0

Вариант №2

In [ ]:
for category in set(data.whoAmI):
    data[category] = [1 if category == val else 0 for val in data.whoAmI]
  
data.head()

  whoAmI  human  robot
0  robot      0      1
1  human      1      0
2  human      1      0
3  robot      0      1
4  robot      0      1

Вариант №3

In [ ]:
unique_value = data.whoAmI.unique()
data[unique_value] = 0
for val in unique_value:
    data.loc[data.whoAmI == val, val] = 1
data.head()

  whoAmI  human  robot
0  robot      0      1
1  human      1      0
2  human      1      0
3  robot      0      1
4  robot      0      1